"""ISO-3166 Countries with Regional Codes
Official country data with UN Geoscheme regional classifications
Data source: https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes
"""

# Complete ISO-3166 country data with regions and sub-regions
ISO_COUNTRIES_DATA = {
    "AF": {"name": "Afghanistan", "region": "Asia", "sub_region": "Southern Asia", "region_code": "142", "sub_region_code": "034"},
    "AX": {"name": "Åland Islands", "region": "Europe", "sub_region": "Northern Europe", "region_code": "150", "sub_region_code": "154"},
    "AL": {"name": "Albania", "region": "Europe", "sub_region": "Southern Europe", "region_code": "150", "sub_region_code": "039"},
    "DZ": {"name": "Algeria", "region": "Africa", "sub_region": "Northern Africa", "region_code": "002", "sub_region_code": "015"},
    "AS": {"name": "American Samoa", "region": "Oceania", "sub_region": "Polynesia", "region_code": "009", "sub_region_code": "061"},
    "AD": {"name": "Andorra", "region": "Europe", "sub_region": "Southern Europe", "region_code": "150", "sub_region_code": "039"},
    "AO": {"name": "Angola", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Middle Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "017"},
    "AI": {"name": "Anguilla", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Caribbean", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "029"},
    "AG": {"name": "Antigua and Barbuda", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Caribbean", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "029"},
    "AR": {"name": "Argentina", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "South America", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "005"},
    "AM": {"name": "Armenia", "region": "Asia", "sub_region": "Western Asia", "region_code": "142", "sub_region_code": "145"},
    "AW": {"name": "Aruba", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Caribbean", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "029"},
    "AU": {"name": "Australia", "region": "Oceania", "sub_region": "Australia and New Zealand", "region_code": "009", "sub_region_code": "053"},
    "AT": {"name": "Austria", "region": "Europe", "sub_region": "Western Europe", "region_code": "150", "sub_region_code": "155"},
    "AZ": {"name": "Azerbaijan", "region": "Asia", "sub_region": "Western Asia", "region_code": "142", "sub_region_code": "145"},
    "BS": {"name": "Bahamas", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Caribbean", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "029"},
    "BH": {"name": "Bahrain", "region": "Asia", "sub_region": "Western Asia", "region_code": "142", "sub_region_code": "145"},
    "BD": {"name": "Bangladesh", "region": "Asia", "sub_region": "Southern Asia", "region_code": "142", "sub_region_code": "034"},
    "BB": {"name": "Barbados", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Caribbean", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "029"},
    "BY": {"name": "Belarus", "region": "Europe", "sub_region": "Eastern Europe", "region_code": "150", "sub_region_code": "151"},
    "BE": {"name": "Belgium", "region": "Europe", "sub_region": "Western Europe", "region_code": "150", "sub_region_code": "155"},
    "BZ": {"name": "Belize", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Central America", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "013"},
    "BJ": {"name": "Benin", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Western Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "011"},
    "BM": {"name": "Bermuda", "region": "Americas", "sub_region": "Northern America", "region_code": "019", "sub_region_code": "021"},
    "BT": {"name": "Bhutan", "region": "Asia", "sub_region": "Southern Asia", "region_code": "142", "sub_region_code": "034"},
    "BO": {"name": "Bolivia", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "South America", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "005"},
    "BQ": {"name": "Bonaire, Sint Eustatius and Saba", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Caribbean", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "029"},
    "BA": {"name": "Bosnia and Herzegovina", "region": "Europe", "sub_region": "Southern Europe", "region_code": "150", "sub_region_code": "039"},
    "BW": {"name": "Botswana", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Southern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "018"},
    "BR": {"name": "Brazil", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "South America", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "005"},
    "BN": {"name": "Brunei", "region": "Asia", "sub_region": "South-eastern Asia", "region_code": "142", "sub_region_code": "035"},
    "BG": {"name": "Bulgaria", "region": "Europe", "sub_region": "Eastern Europe", "region_code": "150", "sub_region_code": "151"},
    "BF": {"name": "Burkina Faso", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Western Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "011"},
    "BI": {"name": "Burundi", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Eastern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "014"},
    "CV": {"name": "Cabo Verde", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Western Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "011"},
    "KH": {"name": "Cambodia", "region": "Asia", "sub_region": "South-eastern Asia", "region_code": "142", "sub_region_code": "035"},
    "CM": {"name": "Cameroon", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Middle Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "017"},
    "CA": {"name": "Canada", "region": "Americas", "sub_region": "Northern America", "region_code": "019", "sub_region_code": "021"},
    "KY": {"name": "Cayman Islands", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Caribbean", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "029"},
    "CF": {"name": "Central African Republic", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Middle Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "017"},
    "TD": {"name": "Chad", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Middle Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "017"},
    "CL": {"name": "Chile", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "South America", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "005"},
    "CN": {"name": "China", "region": "Asia", "sub_region": "Eastern Asia", "region_code": "142", "sub_region_code": "030"},
    "CO": {"name": "Colombia", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "South America", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "005"},
    "KM": {"name": "Comoros", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Eastern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "014"},
    "CG": {"name": "Congo", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Middle Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "017"},
    "CD": {"name": "DR Congo", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Middle Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "017"},
    "CK": {"name": "Cook Islands", "region": "Oceania", "sub_region": "Polynesia", "region_code": "009", "sub_region_code": "061"},
    "CR": {"name": "Costa Rica", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Central America", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "013"},
    "CI": {"name": "Côte d'Ivoire", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Western Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "011"},
    "HR": {"name": "Croatia", "region": "Europe", "sub_region": "Southern Europe", "region_code": "150", "sub_region_code": "039"},
    "CU": {"name": "Cuba", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Caribbean", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "029"},
    "CW": {"name": "Curaçao", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Caribbean", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "029"},
    "CY": {"name": "Cyprus", "region": "Asia", "sub_region": "Western Asia", "region_code": "142", "sub_region_code": "145"},
    "CZ": {"name": "Czechia", "region": "Europe", "sub_region": "Eastern Europe", "region_code": "150", "sub_region_code": "151"},
    "DK": {"name": "Denmark", "region": "Europe", "sub_region": "Northern Europe", "region_code": "150", "sub_region_code": "154"},
    "DJ": {"name": "Djibouti", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Eastern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "014"},
    "DM": {"name": "Dominica", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Caribbean", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "029"},
    "DO": {"name": "Dominican Republic", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Caribbean", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "029"},
    "EC": {"name": "Ecuador", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "South America", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "005"},
    "EG": {"name": "Egypt", "region": "Africa", "sub_region": "Northern Africa", "region_code": "002", "sub_region_code": "015"},
    "SV": {"name": "El Salvador", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Central America", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "013"},
    "GQ": {"name": "Equatorial Guinea", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Middle Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "017"},
    "ER": {"name": "Eritrea", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Eastern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "014"},
    "EE": {"name": "Estonia", "region": "Europe", "sub_region": "Northern Europe", "region_code": "150", "sub_region_code": "154"},
    "SZ": {"name": "Eswatini", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Southern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "018"},
    "ET": {"name": "Ethiopia", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Eastern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "014"},
    "FJ": {"name": "Fiji", "region": "Oceania", "sub_region": "Melanesia", "region_code": "009", "sub_region_code": "054"},
    "FI": {"name": "Finland", "region": "Europe", "sub_region": "Northern Europe", "region_code": "150", "sub_region_code": "154"},
    "FR": {"name": "France", "region": "Europe", "sub_region": "Western Europe", "region_code": "150", "sub_region_code": "155"},
    "GA": {"name": "Gabon", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Middle Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "017"},
    "GM": {"name": "Gambia", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Western Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "011"},
    "GE": {"name": "Georgia", "region": "Asia", "sub_region": "Western Asia", "region_code": "142", "sub_region_code": "145"},
    "DE": {"name": "Germany", "region": "Europe", "sub_region": "Western Europe", "region_code": "150", "sub_region_code": "155"},
    "GH": {"name": "Ghana", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Western Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "011"},
    "GI": {"name": "Gibraltar", "region": "Europe", "sub_region": "Southern Europe", "region_code": "150", "sub_region_code": "039"},
    "GR": {"name": "Greece", "region": "Europe", "sub_region": "Southern Europe", "region_code": "150", "sub_region_code": "039"},
    "GL": {"name": "Greenland", "region": "Americas", "sub_region": "Northern America", "region_code": "019", "sub_region_code": "021"},
    "GD": {"name": "Grenada", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Caribbean", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "029"},
    "GU": {"name": "Guam", "region": "Oceania", "sub_region": "Micronesia", "region_code": "009", "sub_region_code": "057"},
    "GT": {"name": "Guatemala", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Central America", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "013"},
    "GN": {"name": "Guinea", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Western Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "011"},
    "GW": {"name": "Guinea-Bissau", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Western Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "011"},
    "GY": {"name": "Guyana", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "South America", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "005"},
    "HT": {"name": "Haiti", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Caribbean", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "029"},
    "HN": {"name": "Honduras", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Central America", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "013"},
    "HK": {"name": "Hong Kong", "region": "Asia", "sub_region": "Eastern Asia", "region_code": "142", "sub_region_code": "030"},
    "HU": {"name": "Hungary", "region": "Europe", "sub_region": "Eastern Europe", "region_code": "150", "sub_region_code": "151"},
    "IS": {"name": "Iceland", "region": "Europe", "sub_region": "Northern Europe", "region_code": "150", "sub_region_code": "154"},
    "IN": {"name": "India", "region": "Asia", "sub_region": "Southern Asia", "region_code": "142", "sub_region_code": "034"},
    "ID": {"name": "Indonesia", "region": "Asia", "sub_region": "South-eastern Asia", "region_code": "142", "sub_region_code": "035"},
    "IR": {"name": "Iran", "region": "Asia", "sub_region": "Southern Asia", "region_code": "142", "sub_region_code": "034"},
    "IQ": {"name": "Iraq", "region": "Asia", "sub_region": "Western Asia", "region_code": "142", "sub_region_code": "145"},
    "IE": {"name": "Ireland", "region": "Europe", "sub_region": "Northern Europe", "region_code": "150", "sub_region_code": "154"},
    "IL": {"name": "Israel", "region": "Asia", "sub_region": "Western Asia", "region_code": "142", "sub_region_code": "145"},
    "IT": {"name": "Italy", "region": "Europe", "sub_region": "Southern Europe", "region_code": "150", "sub_region_code": "039"},
    "JM": {"name": "Jamaica", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Caribbean", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "029"},
    "JP": {"name": "Japan", "region": "Asia", "sub_region": "Eastern Asia", "region_code": "142", "sub_region_code": "030"},
    "JO": {"name": "Jordan", "region": "Asia", "sub_region": "Western Asia", "region_code": "142", "sub_region_code": "145"},
    "KZ": {"name": "Kazakhstan", "region": "Asia", "sub_region": "Central Asia", "region_code": "142", "sub_region_code": "143"},
    "KE": {"name": "Kenya", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Eastern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "014"},
    "KI": {"name": "Kiribati", "region": "Oceania", "sub_region": "Micronesia", "region_code": "009", "sub_region_code": "057"},
    "KP": {"name": "North Korea", "region": "Asia", "sub_region": "Eastern Asia", "region_code": "142", "sub_region_code": "030"},
    "KR": {"name": "South Korea", "region": "Asia", "sub_region": "Eastern Asia", "region_code": "142", "sub_region_code": "030"},
    "KW": {"name": "Kuwait", "region": "Asia", "sub_region": "Western Asia", "region_code": "142", "sub_region_code": "145"},
    "KG": {"name": "Kyrgyzstan", "region": "Asia", "sub_region": "Central Asia", "region_code": "142", "sub_region_code": "143"},
    "LA": {"name": "Laos", "region": "Asia", "sub_region": "South-eastern Asia", "region_code": "142", "sub_region_code": "035"},
    "LV": {"name": "Latvia", "region": "Europe", "sub_region": "Northern Europe", "region_code": "150", "sub_region_code": "154"},
    "LB": {"name": "Lebanon", "region": "Asia", "sub_region": "Western Asia", "region_code": "142", "sub_region_code": "145"},
    "LS": {"name": "Lesotho", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Southern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "018"},
    "LR": {"name": "Liberia", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Western Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "011"},
    "LY": {"name": "Libya", "region": "Africa", "sub_region": "Northern Africa", "region_code": "002", "sub_region_code": "015"},
    "LI": {"name": "Liechtenstein", "region": "Europe", "sub_region": "Western Europe", "region_code": "150", "sub_region_code": "155"},
    "LT": {"name": "Lithuania", "region": "Europe", "sub_region": "Northern Europe", "region_code": "150", "sub_region_code": "154"},
    "LU": {"name": "Luxembourg", "region": "Europe", "sub_region": "Western Europe", "region_code": "150", "sub_region_code": "155"},
    "MG": {"name": "Madagascar", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Eastern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "014"},
    "MW": {"name": "Malawi", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Eastern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "014"},
    "MY": {"name": "Malaysia", "region": "Asia", "sub_region": "South-eastern Asia", "region_code": "142", "sub_region_code": "035"},
    "MV": {"name": "Maldives", "region": "Asia", "sub_region": "Southern Asia", "region_code": "142", "sub_region_code": "034"},
    "ML": {"name": "Mali", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Western Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "011"},
    "MT": {"name": "Malta", "region": "Europe", "sub_region": "Southern Europe", "region_code": "150", "sub_region_code": "039"},
    "MH": {"name": "Marshall Islands", "region": "Oceania", "sub_region": "Micronesia", "region_code": "009", "sub_region_code": "057"},
    "MR": {"name": "Mauritania", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Western Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "011"},
    "MU": {"name": "Mauritius", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Eastern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "014"},
    "MX": {"name": "Mexico", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Central America", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "013"},
    "FM": {"name": "Micronesia", "region": "Oceania", "sub_region": "Micronesia", "region_code": "009", "sub_region_code": "057"},
    "MD": {"name": "Moldova", "region": "Europe", "sub_region": "Eastern Europe", "region_code": "150", "sub_region_code": "151"},
    "MC": {"name": "Monaco", "region": "Europe", "sub_region": "Western Europe", "region_code": "150", "sub_region_code": "155"},
    "MN": {"name": "Mongolia", "region": "Asia", "sub_region": "Eastern Asia", "region_code": "142", "sub_region_code": "030"},
    "ME": {"name": "Montenegro", "region": "Europe", "sub_region": "Southern Europe", "region_code": "150", "sub_region_code": "039"},
    "MA": {"name": "Morocco", "region": "Africa", "sub_region": "Northern Africa", "region_code": "002", "sub_region_code": "015"},
    "MZ": {"name": "Mozambique", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Eastern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "014"},
    "MM": {"name": "Myanmar", "region": "Asia", "sub_region": "South-eastern Asia", "region_code": "142", "sub_region_code": "035"},
    "NA": {"name": "Namibia", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Southern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "018"},
    "NR": {"name": "Nauru", "region": "Oceania", "sub_region": "Micronesia", "region_code": "009", "sub_region_code": "057"},
    "NP": {"name": "Nepal", "region": "Asia", "sub_region": "Southern Asia", "region_code": "142", "sub_region_code": "034"},
    "NL": {"name": "Netherlands", "region": "Europe", "sub_region": "Western Europe", "region_code": "150", "sub_region_code": "155"},
    "NC": {"name": "New Caledonia", "region": "Oceania", "sub_region": "Melanesia", "region_code": "009", "sub_region_code": "054"},
    "NZ": {"name": "New Zealand", "region": "Oceania", "sub_region": "Australia and New Zealand", "region_code": "009", "sub_region_code": "053"},
    "NI": {"name": "Nicaragua", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Central America", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "013"},
    "NE": {"name": "Niger", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Western Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "011"},
    "NG": {"name": "Nigeria", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Western Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "011"},
    "NO": {"name": "Norway", "region": "Europe", "sub_region": "Northern Europe", "region_code": "150", "sub_region_code": "154"},
    "OM": {"name": "Oman", "region": "Asia", "sub_region": "Western Asia", "region_code": "142", "sub_region_code": "145"},
    "PK": {"name": "Pakistan", "region": "Asia", "sub_region": "Southern Asia", "region_code": "142", "sub_region_code": "034"},
    "PW": {"name": "Palau", "region": "Oceania", "sub_region": "Micronesia", "region_code": "009", "sub_region_code": "057"},
    "PS": {"name": "Palestine", "region": "Asia", "sub_region": "Western Asia", "region_code": "142", "sub_region_code": "145"},
    "PA": {"name": "Panama", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Central America", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "013"},
    "PG": {"name": "Papua New Guinea", "region": "Oceania", "sub_region": "Melanesia", "region_code": "009", "sub_region_code": "054"},
    "PY": {"name": "Paraguay", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "South America", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "005"},
    "PE": {"name": "Peru", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "South America", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "005"},
    "PH": {"name": "Philippines", "region": "Asia", "sub_region": "South-eastern Asia", "region_code": "142", "sub_region_code": "035"},
    "PL": {"name": "Poland", "region": "Europe", "sub_region": "Eastern Europe", "region_code": "150", "sub_region_code": "151"},
    "PT": {"name": "Portugal", "region": "Europe", "sub_region": "Southern Europe", "region_code": "150", "sub_region_code": "039"},
    "PR": {"name": "Puerto Rico", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Caribbean", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "029"},
    "QA": {"name": "Qatar", "region": "Asia", "sub_region": "Western Asia", "region_code": "142", "sub_region_code": "145"},
    "RO": {"name": "Romania", "region": "Europe", "sub_region": "Eastern Europe", "region_code": "150", "sub_region_code": "151"},
    "RU": {"name": "Russia", "region": "Europe", "sub_region": "Eastern Europe", "region_code": "150", "sub_region_code": "151"},
    "RW": {"name": "Rwanda", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Eastern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "014"},
    "KN": {"name": "Saint Kitts and Nevis", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Caribbean", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "029"},
    "LC": {"name": "Saint Lucia", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Caribbean", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "029"},
    "VC": {"name": "Saint Vincent", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Caribbean", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "029"},
    "WS": {"name": "Samoa", "region": "Oceania", "sub_region": "Polynesia", "region_code": "009", "sub_region_code": "061"},
    "SM": {"name": "San Marino", "region": "Europe", "sub_region": "Southern Europe", "region_code": "150", "sub_region_code": "039"},
    "ST": {"name": "Sao Tome", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Middle Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "017"},
    "SA": {"name": "Saudi Arabia", "region": "Asia", "sub_region": "Western Asia", "region_code": "142", "sub_region_code": "145"},
    "SN": {"name": "Senegal", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Western Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "011"},
    "RS": {"name": "Serbia", "region": "Europe", "sub_region": "Southern Europe", "region_code": "150", "sub_region_code": "039"},
    "SC": {"name": "Seychelles", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Eastern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "014"},
    "SL": {"name": "Sierra Leone", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Western Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "011"},
    "SG": {"name": "Singapore", "region": "Asia", "sub_region": "South-eastern Asia", "region_code": "142", "sub_region_code": "035"},
    "SK": {"name": "Slovakia", "region": "Europe", "sub_region": "Eastern Europe", "region_code": "150", "sub_region_code": "151"},
    "SI": {"name": "Slovenia", "region": "Europe", "sub_region": "Southern Europe", "region_code": "150", "sub_region_code": "039"},
    "SB": {"name": "Solomon Islands", "region": "Oceania", "sub_region": "Melanesia", "region_code": "009", "sub_region_code": "054"},
    "SO": {"name": "Somalia", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Eastern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "014"},
    "ZA": {"name": "South Africa", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Southern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "018"},
    "SS": {"name": "South Sudan", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Eastern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "014"},
    "ES": {"name": "Spain", "region": "Europe", "sub_region": "Southern Europe", "region_code": "150", "sub_region_code": "039"},
    "LK": {"name": "Sri Lanka", "region": "Asia", "sub_region": "Southern Asia", "region_code": "142", "sub_region_code": "034"},
    "SD": {"name": "Sudan", "region": "Africa", "sub_region": "Northern Africa", "region_code": "002", "sub_region_code": "015"},
    "SR": {"name": "Suriname", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "South America", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "005"},
    "SE": {"name": "Sweden", "region": "Europe", "sub_region": "Northern Europe", "region_code": "150", "sub_region_code": "154"},
    "CH": {"name": "Switzerland", "region": "Europe", "sub_region": "Western Europe", "region_code": "150", "sub_region_code": "155"},
    "SY": {"name": "Syria", "region": "Asia", "sub_region": "Western Asia", "region_code": "142", "sub_region_code": "145"},
    "TW": {"name": "Taiwan", "region": "Asia", "sub_region": "Eastern Asia", "region_code": "142", "sub_region_code": "030"},
    "TJ": {"name": "Tajikistan", "region": "Asia", "sub_region": "Central Asia", "region_code": "142", "sub_region_code": "143"},
    "TZ": {"name": "Tanzania", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Eastern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "014"},
    "TH": {"name": "Thailand", "region": "Asia", "sub_region": "South-eastern Asia", "region_code": "142", "sub_region_code": "035"},
    "TL": {"name": "Timor-Leste", "region": "Asia", "sub_region": "South-eastern Asia", "region_code": "142", "sub_region_code": "035"},
    "TG": {"name": "Togo", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Western Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "011"},
    "TO": {"name": "Tonga", "region": "Oceania", "sub_region": "Polynesia", "region_code": "009", "sub_region_code": "061"},
    "TT": {"name": "Trinidad & Tobago", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "Caribbean", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "029"},
    "TN": {"name": "Tunisia", "region": "Africa", "sub_region": "Northern Africa", "region_code": "002", "sub_region_code": "015"},
    "TR": {"name": "Türkiye", "region": "Asia", "sub_region": "Western Asia", "region_code": "142", "sub_region_code": "145"},
    "TM": {"name": "Turkmenistan", "region": "Asia", "sub_region": "Central Asia", "region_code": "142", "sub_region_code": "143"},
    "TV": {"name": "Tuvalu", "region": "Oceania", "sub_region": "Polynesia", "region_code": "009", "sub_region_code": "061"},
    "UG": {"name": "Uganda", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Eastern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "014"},
    "UA": {"name": "Ukraine", "region": "Europe", "sub_region": "Eastern Europe", "region_code": "150", "sub_region_code": "151"},
    "AE": {"name": "UAE", "region": "Asia", "sub_region": "Western Asia", "region_code": "142", "sub_region_code": "145"},
    "GB": {"name": "United Kingdom", "region": "Europe", "sub_region": "Northern Europe", "region_code": "150", "sub_region_code": "154"},
    "US": {"name": "United States", "region": "Americas", "sub_region": "Northern America", "region_code": "019", "sub_region_code": "021"},
    "UY": {"name": "Uruguay", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "South America", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "005"},
    "UZ": {"name": "Uzbekistan", "region": "Asia", "sub_region": "Central Asia", "region_code": "142", "sub_region_code": "143"},
    "VU": {"name": "Vanuatu", "region": "Oceania", "sub_region": "Melanesia", "region_code": "009", "sub_region_code": "054"},
    "VE": {"name": "Venezuela", "region": "Americas", "sub_region": "Latin America and the Caribbean", "intermediate_region": "South America", "region_code": "019", "sub_region_code": "419", "intermediate_region_code": "005"},
    "VN": {"name": "Vietnam", "region": "Asia", "sub_region": "South-eastern Asia", "region_code": "142", "sub_region_code": "035"},
    "YE": {"name": "Yemen", "region": "Asia", "sub_region": "Western Asia", "region_code": "142", "sub_region_code": "145"},
    "ZM": {"name": "Zambia", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Eastern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "014"},
    "ZW": {"name": "Zimbabwe", "region": "Africa", "sub_region": "Sub-Saharan Africa", "intermediate_region": "Eastern Africa", "region_code": "002", "sub_region_code": "202", "intermediate_region_code": "014"},
}


def get_country_info(alpha_2_code: str) -> dict:
    """Get country information by ISO Alpha-2 code"""
    return ISO_COUNTRIES_DATA.get(alpha_2_code.upper(), {})


def get_countries_by_region(region: str) -> list:
    """Get all countries in a specific region"""
    return [
        {"code": code, **data}
        for code, data in ISO_COUNTRIES_DATA.items()
        if data.get("region", "").lower() == region.lower()
    ]


def get_countries_by_sub_region(sub_region: str) -> list:
    """Get all countries in a specific sub-region"""
    return [
        {"code": code, **data}
        for code, data in ISO_COUNTRIES_DATA.items()
        if data.get("sub_region", "").lower() == sub_region.lower()
    ]


def get_all_regions() -> list:
    """Get list of all unique regions"""
    regions = set()
    for data in ISO_COUNTRIES_DATA.values():
        if data.get("region"):
            regions.add(data["region"])
    return sorted(list(regions))


def get_all_sub_regions() -> list:
    """Get list of all unique sub-regions"""
    sub_regions = set()
    for data in ISO_COUNTRIES_DATA.values():
        if data.get("sub_region"):
            sub_regions.add(data["sub_region"])
    return sorted(list(sub_regions))
